### ISSUE TITLE
Code Lab Feedback

### ISSUE THREAD

**Issue by KatieMFritz** [KatieMFritz/codelab-sinatra-helper-methods#2]
Hey @chrisvfritz, can you take a look at this? It's [hosted here](https://shrouded-everglades-2296.herokuapp.com/) and meets the following [project](http://lansingcodelab.com/lessons/sinatra-helper-methods/1) criteria:
- [x] Define and use a method called `pluralize` in your app. It should take two parameters: `singular_name` and `count`. `pluralize('cat', 5)` should return `'5 cats'`, `pluralize('cat', 1)` should return `'1 cat'`, and `pluralize('cat', 0)` should return `'0 cats'`.
- [x] Define and use a method called `use_google_font` in your app. It should take a single parameter: `font`. It should return the `link` element to include the font and a `style` element that applies the font to the body. Example usage would be `use_google_font('Open Sans')`. This one requires you know how to [customize the fonts in a webpage](http://lansingcodelab.com/lessons/css-font-families/1), so complete or review that lesson if you need to.
- [x] Define and use a method called `icon_button` in your app. It should take 3 parameters: `icon`, `type` (with a default value of `'default'`), and `message`, with a default value of `''`. That means the only required parameter is `icon`. It should return a button with an icon, similar to the [example in the Bootstrap docs](http://getbootstrap.com/components/#glyphicons-examples). Note that Bootstrap must be correctly included in your app for this to work.

**Comment by KatieMFritz** [comment]
Ooh. fakout... it's not pushing to Heroku properly. Here's what's in my console:
`$ git push heroku master
Counting objects: 195, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (187/187), done.
Writing objects: 100% (195/195), 575.70 KiB | 0 bytes/s, done.
Total 195 (delta 15), reused 0 (delta 0)
remote: Compressing source files... done.
remote: Building source:
remote:
remote: -----> Ruby app detected
remote: -----> Compiling Ruby/NoLockfile
remote:  !
remote:  !     Gemfile.lock required. Please check it in.
remote:  !
remote:
remote:  !     Push rejected, failed to compile Ruby app
remote:
remote: Verifying deploy....
remote:
remote: !       Push rejected to shrouded-everglades-2296.
remote:
To https://git.heroku.com/shrouded-everglades-2296.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/shrouded-everglades-2296.git'`

**Comment by KatieMFritz** [comment]
Got it! I hadn't run bundle install on this project, so the Gemfile.lock hadn't been created. Once I did that and added/committed/pushed everything, it worked.

**Comment by chrisvfritz** [comment]
The code itself is looking good, but the formatting of the code still needs some work. 

For example, taking a look at [your `app.rb`](https://github.com/KatieMFritz/codelab-sinatra-helper-methods/blob/master/app.rb), it looks like partway through the file you switch from 2-space soft tabs to hard tabs. In Ruby, it's convention to use two-space soft tabs and I personally feel like that's the best convention for _any_ language, so can you change the indentation settings in Atom use that? For current files, it may also be useful to tell atom to show whitespace, which is another setting. And finally, [this plugin](https://atom.io/packages/tabs-to-spaces) may also be helpful for converting existing files.

The second thing I see is some inconsistent indentation between `use_google_font` and `icon_button`. In the former, HTML inside the string is indented, but not in the latter. Either form is acceptable, but I would choose one and stick to it.

**Comment by KatieMFritz** [comment]
@chrisvfritz Can you take another look? Not sure if I did things right. It might help for you to look at atom with me.

**Comment by KatieMFritz** [comment]
@chrisvfritz How is this now? I think it's all spaces now, not tabs.

**Comment by chrisvfritz** [comment]
I still see [tabs here](https://github.com/KatieMFritz/codelab-sinatra-helper-methods/blob/master/app.rb#L27-L29).

**Comment by KatieMFritz** [comment]
Gahhhhh how about now?

**Comment by chrisvfritz** [comment]
:shipit:
